using System.Reflection;
[assembly: AssemblyTitle ("INDISharp")]
[assembly: AssemblyDescription ("INDI C# Assembly")]
[assembly: AssemblyConfiguration ("")]
[assembly: AssemblyCompany ("")]
[assembly: AssemblyProduct ("")]
[assembly: AssemblyCopyright ("Ilia Platone")]
[assembly: AssemblyTrademark ("")]
[assembly: AssemblyCulture ("")]
[assembly: AssemblyVersion ("0.10.0.*")]
